CREATE TABLE IF NOT EXISTS `infomation`(
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`user_id` INT UNSIGNED DEFAULT NULL,
`title` VARCHAR(50) DEFAULT NULL,
`thumb` VARCHAR(100) DEFAULT NULL,
`author` CHAR(12) DEFAULT NULL,
`content` TEXT DEFAULT NULL,
`listorder` smallint(6) UNSIGNED NOT NULL DEFAULT '0',
`created_at` int(21) UNSIGNED DEFAULT '0',
`updated_at` int(21) UNSIGNED DEFAULT '0',
PRIMARY KEY (`id`),
KEY `user_id`(`user_id`)
)ENGINE=MyISAM DEFAULT CHARSET=utf8;