<?php
// ////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2015-2016 Hangzhou Freewind Technology Co., Ltd.
// All rights reserved.
// http://www.seastart.cn
//
// ///////////////////////////////////////////////////////////////////////////
namespace api\modules\v1\controllers;

/**
 * user controller
 *
 * @author Ather.Shu Apr 22, 2015 1:59:30 PM
 */
class UserController extends \api\common\controllers\UserController {

    /*public function actionLogin()
    {
        return "LOGIN已調用";
        //return parent::actionLogin(); // TODO: Change the autogenerated stub
    }*/



}